spring.application.name=SpringBoot2026

spring.datasource.url=${DB_SCHEMA_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=none
